# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial
    time: 08:00:00 # time limit for each job
    cpus-per-task: 2
    mem: 16G
    output: results/logs/slurm-%x.%A.%a.log
    error: results/errors/slurm-%x.%A.%a.err

call_peaks_with_macs2:
    cpus-per-task: 2
    mem: 16G
    cores: 2
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.sample}.slurm-%x.%A.%a.err

generate_consensus_peaks:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    name: "{rule}.{wildcards.Set}"
    output: results/logs/{rule}.{wildcards.Set}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.Set}.slurm-%x.%A.%a.err

make_bed_of_reproducible_peaks:
    cpus-per-task: 2
    mem: 16G
    cores: 2
    name: "{rule}.{wildcards.Set}"
    output: results/logs/{rule}.{wildcards.Set}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.Set}.slurm-%x.%A.%a.err

create_bam_from_consensus:
    cpus-per-task: 4
    mem: 16G
    cores: 2
    name: "{rule}.{wildcards.Set}"
    output: results/logs/{rule}.{wildcards.Set}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.Set}.slurm-%x.%A.%a.err

create_bigwig_from_consensus:
    cpus-per-task: 4
    mem: 16G
    cores: 2
    name: "{rule}.{wildcards.Set}"
    output: results/logs/{rule}.{wildcards.Set}.slurm-%x.%A.%a.log
    error: results/errors/{rule}.{wildcards.Set}.slurm-%x.%A.%a.err
