# samples file
samples_csv: "config/samples.csv"

# genome-of-interest
genome: "hs"
BSgenomeRPackage: "BSgenome.Hsapiens.UCSC.hg38"

# effective genome size
effective_genome_size: 2913022398

# macs2 options
macs2_qvalue: 0.05
minNumberOfSampleOverlaps: 2

# bamCoverage options
binSize: 50

# Euler plot parameters
EulerFontSize: 8                # Base font size for the Euler plot
EulerColors: "red,green,blue"   # Comma-separated colors for the plot
EulerWidth: 5                   # Width of the PDF plot in inches
EulerHeight: 5                  # Height of the PDF plot in inches

# environment modules
deeptools: "deeptools/3.4.3"
macs2: "macs2/2.2.7.1"
samtools: "samtools/1.14"
bedtools: "bedtools/2.30.0"
R: "R/4.1.2-mkl"
bioconductor: "bioconductor/3.19 gsl"
